# Programa Ingenias+ Data Science

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria o modulo.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion NumPy](https://devdocs.io/numpy/)

## Clase 4: Introduccion a NumPy

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [2]:
import numpy as np

In [2]:
arr = np.zeros(12)

In [3]:
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
#Ejercicio 2
array1 = np.zeros(10)
array1[4] = 10

array1


array([ 0.,  0.,  0.,  0., 10.,  0.,  0.,  0.,  0.,  0.])

In [7]:
#Ejercicio 3
array2 = np.arange(10,50)
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [8]:
#Ejercicio 4 (se puede mejorar)
lista = [[0,1,2], [3,4,5], [6,7,8]]

array3 = np.array(lista)
array3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
# Otra posibilidad
new_array = np.arange(9).reshape(3,3)
new_array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
#Ejercicio 5
array4 = np.random.randint(0,100,100)
array4.size
array4



array([12, 13, 12, 58,  8, 64, 36, 60, 76, 44, 24, 93,  0, 12, 91,  5, 31,
       78, 40, 51, 39, 75, 44, 46, 93, 25, 38, 69, 52, 73, 74, 50, 13, 33,
       85, 24,  3, 97, 48, 84, 55, 27, 43, 26, 92, 46, 49, 12, 11, 59, 91,
       96, 89, 27, 31, 60,  4, 82,  7, 81, 13, 58, 99, 72, 22, 36, 78, 38,
       87, 27, 59, 19, 42, 10,  5, 11, 90, 31, 30, 67, 52, 45, 25, 26, 72,
       21, 59, 72, 84, 68, 54, 42, 69, 38,  3,  6, 86, 26,  2, 10])

In [15]:
array4.mean()

46.15

In [16]:
array4.var()

816.4675000000002

In [17]:
#Ejercicio 6
array4.sum()/array4.size

46.15

In [18]:
#Ejercicio 7
#Calculamos la media
media = array4.mean()

#Calculamos la diferencia al cuadrado
diferencia_al_cuadrado = (array4 - media)**2

#sumamos diferencias al cuadrado
suma_diferencias_al_cuadrado = np.sum(diferencia_al_cuadrado)

#Dividimos la suma, por el numero de elementos que tiene el array
varianza = suma_diferencias_al_cuadrado / array4.size

print('La varianza de {} es de {}'.format(array4, varianza))



La varianza de [12 13 12 58  8 64 36 60 76 44 24 93  0 12 91  5 31 78 40 51 39 75 44 46
 93 25 38 69 52 73 74 50 13 33 85 24  3 97 48 84 55 27 43 26 92 46 49 12
 11 59 91 96 89 27 31 60  4 82  7 81 13 58 99 72 22 36 78 38 87 27 59 19
 42 10  5 11 90 31 30 67 52 45 25 26 72 21 59 72 84 68 54 42 69 38  3  6
 86 26  2 10] es de 816.4675000000002


In [28]:
#Ejercicio 8
array6 = np.random.randn(20)
array6

array([-0.59430626, -0.07130071, -0.11522455,  0.87859195, -1.44277963,
       -0.37336925, -1.35924413, -1.07260018, -0.36258473,  0.55684827,
        1.42362698, -0.22117451,  0.51513076, -0.11184139, -0.32963013,
       -0.63741283, -0.76181684,  1.32752004, -0.22076085,  0.02614857])

In [9]:
media = array4.mean()
# Suma de diferencias cuadradas de cada dato respecto a la media
suma_diferencias_cuadradas = sum ([(i - media) ** 2 for i in array4])
varianza = suma_diferencias_cuadradas / (array4.size)
print("Varianza: ",varianza)

Varianza:  910.1976


In [19]:
varianza_con_sum_mean = np.sum((array4 - np.mean(array4))**2) / len(array4)

varianza_con_sum_mean

816.4675000000002

In [20]:
array4.var()

816.4675000000002